version: "3.8"

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.sample
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./backend/data:/data

volumes:
   data:
